export const lines = [
  'This is how time works  we see    everything at once    we don’t',
  ' separate moments      My mother walks the driveway    singing',
  '  in her latter years    with    laundry basket',
  '  & at the same time      I am being born      & she takes photos',
  '   at my graduation    & my second graduation    & at the same time  ',
  '    she is standing on a tennis court    in high school uniform  & somewhere still',
  '     she doesn’t exist    & neither do   I  The fabric of time    tears open  & ',
  '      folds   over  & there    is a tidal wave rising here    soon      ‘',
  '       we can feel it     I photograph  picket signs    & at the same time',
  '        photographs are still being  invented    white lace    on pieces of card',
  '         & at the same time    my body decomposes underground',
  '          worms crawl    through my eyes      like I am a castle',
  '           If we travel   through  time  like space  we won’t like    what we find',
  '            but we can hypothesise things    anyway    until the cows  come  ',
  '             This is how time works    we go back    & back    & back',
  '              My tīpuna  stand    on the shore  welcoming    & get shot for it',
  '                I see     blood spots  on the sand    & at the same time    ',
  '                 the ship never comes      we thrive',
  '                   & at the same time   we fight    our cousins  anyway  over kaimoana',
  '                     If we travel back far enough',
  '                      There’ll be things',
  '                        we don’t want to see      Time frays   tattered    at the edges',
  '                          & I want all of it    at once  enveloping me',
  '                            I hunger    to know what has happened    & what might ',
  '                              &   what will    to find a  hole  in the atmosphere',
  '                                force open    & explore it',
  '                                 even if it hurts    ',
  '                                   This is how time works    we create formulas    & escape',
  '                                    into fantasy',
  '                                     My mokopuna wear  solar powered shoes',
  '                                     that let them fly    & at the same time  I never had children',
  '                                      we sit    silent  in a doctor’s office',
  '                                      & at the same time      my dad is a young man  cycling',
  '                                       the north island    & at the same time  that island’s',
  '                                       being fished  from the sea',
  '                                        sweat on Maui’s forearms  the sun beating  & being beaten',
  '                                        all of these moments      weaving into each other',
  '                           the tarmac    rumble  s  underneath us',
  '                                                        time tearing    apart    apart',
  '                                I am so scared    of an ending',
  '                                           sometimes',
  '                                           I feel like',
  '                                           I could just  ',
  '                                             dis      ha',
  '                                             ap          ha',
  '                                             pe',
  '                                            a    ha    ha      ',
  '                                            r',
  '                                            But',
  '                                           then again',
  '                                           we’re all   still    here',
  '                                           I carve my name',
  '                                          on the arm of an    airplane seat',
  '                                          &    we shoot through space    me & she',
  '                                         with hands clasped    tight',
  '                                         we’re at the beginning of a journey    & at the middle',
  '                                        & the end                   ',
  '                                        but in this instance    we’re ',
  '                                       just talking    time weaves    around us',
  '                                      in our pocket of sky  ',
  '                                     & if I could have anything  in all of the parallel universes',
  '                                    it would be this',
];
export default lines;
